### ISSUE TITLE
old tag

### ISSUE THREAD

**Issue by bealdav** [OCA/openupgradelib#103]
Hi there are recent commits here, but no recent version tag here.

Some of these commits are required by odoo account module.

What can I do to help ?

**Comment by pedrobaeza** [comment]
I don't get you... you can always use `pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master` for having latest version.

**Comment by bealdav** [comment]
Yes, I've solve it, but it's for those which don't know they need to work on dev they could be disturbed
