### ISSUE TITLE
Rename a module

### ISSUE THREAD

**Issue by dreispt** [OCA/openupgradelib#107]
Renaming a module is something that is useful for community modules.
A particular case that I'm concerned about are previously built modules that are then proposed the OCA, and must change their technical name to meet the OCA guidelines.

The lib already provides all the helpers needed to achieve this, but I miss a higher level function to do that.
Would that be a good addition to the library?

**Comment by StefanRijnhart** [comment]
Do you mean https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L932?

**Comment by pedrobaeza** [comment]
We are doing this everyday. Check https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/addons/openupgrade_records/lib/apriori.py

**Comment by StefanRijnhart** [comment]
@pedrobaeza it's more polite to only close the issue after the submitter confirmed that the issue is solved ;-)

**Comment by pedrobaeza** [comment]
That's not GTD, and politeness IMO is to answer instead of doing nothing. If not closing this, we have opened issues that are not relevant anymore. You only have to check the current number of opened things to know that the "politeness approach" doesn't work.

**Comment by StefanRijnhart** [comment]
I'm less worried about the open issues than the number of active participants. Politeness may help to increase the latter.

**Comment by pedrobaeza** [comment]
That's not the case, as Daniel is enough familiar to all of us for not understanding this.

**Comment by StefanRijnhart** [comment]
I wasn't talking about Daniel in particular, although I do feel that I was engaging in a conversation with him that was now cut off. I would have liked to hear from him if this method was what he had in mind, or if he has ideas about possible improvements. If an issue is closed abruptly, such a conversation might not take place.

**Comment by pedrobaeza** [comment]
Why not? He would see the answer, and say "It's OK. That's what I was looking for". Everything correct and nothing more to do.

If not, then he replies and can reopen the issue (or you if the other party doesn't have the privileges).

**Comment by dreispt** [comment]
Thank you, I did check the code but it looks like I missed that function.

(Yes, no offense taken by the fast close of course, but I agree that as a general rule it is polite to wait a reasonable time for a confirmation from the other side).

**Comment by pedrobaeza** [comment]
Well, that's not my general rule, but when the percentage of "matched answer" is high, I do it as said for avoiding opened things that are not real. On contrary, you need more time to revisit all these issues (as I have to do it over OCA and Odoo - you can see my days where I do it on my GH history -), I think it's more efficient this way for those where I can get the understanding of my "rudeness".

**Comment by hbrunn** [comment]
did someone once talk about preferring to ask for forgiveness instead of asking for permission?
