### ISSUE TITLE
Odoo is releasing similar tools in core

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/openupgradelib#116]
It seems Odoo is publishing similar tools that those we have in this library in the core:

https://github.com/odoo/odoo/pull/26548/files#diff-88bb0c3f4288be63142d7287759e3101

**Comment by StefanRijnhart** [comment]
This can only mean one thing.

**Comment by pedrobaeza** [comment]
Yeah, I think this is going to be the moment.

cc @OCA/board

**Comment by thomaspaulb** [comment]
Intentionally cryptic?

**Comment by pedrobaeza** [comment]
Well, Odoo has finally closed the PR, so our hope has vanished. Closing this as it was only informational.

@thomaspaulb we had the hope of Odoo open sourcing migration scripts.
