### ISSUE TITLE
merge_records: compatible with ondelete restrict

### ISSUE THREAD

**Issue by mreficent** [OCA/openupgradelib#125]
Suppose you are merging records of a model A with merge_records method. Then, if those records are used in another model B using a many2one with `ondelete=restrict`, then it breaks.

To solve this, the method should be adapted to include this case: before doing the deletion of the record of model A, it should change the records of model B that reference that record with the new id.

I would do it myself, but I am a bit confused on where the exact code change should be done.

**Comment by pedrobaeza** [comment]
It shouldn't be any problem. Check the order in 

https://github.com/OCA/openupgradelib/blob/0ac601497c9849c3f257ca505bc00d28af368155/openupgradelib/openupgrade_merge_records.py#L443

First, you change references, and at the end is when you unlink old records. Have you found any real problem or you are only theorizing about this?

**Comment by mreficent** [comment]
When testing https://github.com/OCA/OpenUpgrade/pull/1619 on a database with some duplicated `res.country.state` records, in the post-migration, I receive this error:

IntegrityError: update or delete on table "res_country_state" violates foreign key constraint "res_partner_state_id_fkey" on table "res_partner"
DETAIL:  Key (id)=(3924) is still referenced from table "res_partner".

I supposed that it because `res.partner` has `ondelete=restrict` in `country_id` and `state_id`.

**Comment by pedrobaeza** [comment]
Are you using SQL or ORM. SQL is not fully implemented. That can be the reason. I see also a lot of other code in your PR that can be the source. Is that code really needed? I think it can be simplified if needed.

**Comment by mreficent** [comment]
It's using ORM (that's what is marked as default).

**Comment by pedrobaeza** [comment]
Then it should be another thing as stated. Can you share demo set and full stack trace?
