### ISSUE TITLE
map_values cannot properly map the 3 states of a Postgresql Boolean column

### ISSUE THREAD

**Issue by rvalyi** [OCA/openupgradelib#133]
In Postgres, a Boolean can have 3 states:
true, false and unknown: https://www.postgresql.org/docs/10/datatype-boolean.html

However in in the code of the map_values function we have:
```
    for old, new in mapping:
        new = "'%s'" % new

        if old is True:
            old = 'NOT NULL'
            op = 'IS'
        elif old is False:
            old = 'NULL'
            op = 'IS'
        else:
            old = "'%s'" % old
            op = '='

        values = {
            'table': table,
            'source': source_column,
            'target': target_column,
            'old': old,
            'new': new,
            'op': op,
        }

        if write == 'sql':
            query = """UPDATE %(table)s
                       SET %(target)s = %(new)s
                       WHERE %(source)s %(op)s %(old)s""" % values
        else:
            query = """SELECT id FROM %(table)s
                       WHERE %(source)s %(op)s %(old)s""" % values
        logged_query(cr, query, values)
```

So if we want to do a mapping such as defined here:

```
def map_product_attribute_create_variant(cr):
    openupgrade.map_values(
        cr,
        openupgrade.get_legacy_name('create_variant'),
        'create_variant',
        [(False, 'no_variant'),
         (None, 'no_variant'),
         (True, 'always'),
         ],
        table='product_attribute', write='sql')
```
( see https://github.com/Eficent/OpenUpgrade/blob/12.0-mig-product/addons/product/migrations/12.0.1.2/post-migration.py the branch has errors which I am fixing but it can be used as reference to understand)

We cannot because:

1. False will be transformed to IS NULL (which different of False for a Boolean Postgres type)
2. We have no way to use the NULL value as the source to be mapped

cc @mreficent (I used you branch to discover this issue, I don't know how you worked around it)

**Comment by rvalyi** [comment]
@mreficent BTW with your original post-migration script I get this error with the None mapping:
```
  File "/odoo/src/addons/product/migrations/12.0.1.2/post-migration.py", line 15, in map_product_attribute_create_variant
    table='product_attribute', write='sql')
  File "/src/openupgradelib/openupgradelib/openupgrade.py", line 1219, in map_values
    logged_query(cr, query, values)
  File "/src/openupgradelib/openupgradelib/openupgrade.py", line 929, in logged_query
    cr.execute(query, args)
  File "/odoo/src/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/src/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for type boolean: "None"
LINE 3: ...       WHERE openupgrade_legacy_12_0_create_variant = 'None'
```
(and also your pre-migration.py script has an error as you used the 'res_partner' table instead of the 'product_attribute' table, but I'm fixing this in an OpenUpgrade PR that also rebases the work done here https://github.com/OCA/OpenUpgrade/pull/1533 )

**Comment by rvalyi** [comment]
@mreficent your branch is a WIP of course, but it is a code that illustrates the limitation of the current mapping method. I think I remember the Odoo ORM makes no difference between null Boolean and False Boolean, so may be the issue is not so visible, still I think it exists.

Now just some of topic as you are here: you might be interested in these 2 forks of 2 of your OpenUpgrade v12 branches:

1. https://github.com/akretion/OpenUpgrade/tree/12.0-product-uom This is a rebase of https://github.com/OCA/OpenUpgrade/pull/1533 that includes your 2.0-mig-product branch and fixes it. (I will propose it in OpenUpgrade, what do you think?)
2. https://github.com/akretion/OpenUpgrade/tree/12.0-mig-account that is a fork of your 12.0-mig-account but cleans up things that depend and on the stock and sale modules. May be it helps you.

You can reach me on raphael.valyi at akretion.com to discuss this further, I have very limited resource to dedicate on OpenUpgrade in this project, but certainly I can review your work and help you on some points.

**Comment by mreficent** [comment]
Thanks, but prefer you wait until I do my PRs and then you do a review of them. It seems a lot weird to me if you took my WIP work and you do the PRs instead of myself.

**Comment by mreficent** [comment]
Another way of approach is that you do a PR to my branches :)

**Comment by rvalyi** [comment]
@mreficent well in fact I reused https://github.com/OCA/OpenUpgrade/pull/1533 which you didn't reuse (for the new uom module). I also preserved your commits. I can do a PR in your branch, but since you skipped ttps://github.com/OCA/OpenUpgrade/pull/1533 it's not going to be merge-able...

**Comment by mreficent** [comment]
I will also reuse it, don't worry.

**Comment by pedrobaeza** [comment]
The method is not intended for that purpose right now. There's no easy way to deal with that either, so I prefer to not cover that case and do it through direct SQL queries in the migration scripts.
