### ISSUE TITLE
Error in Openupgrade V7

### ISSUE THREAD

**Issue by javierjcf** [OCA/openupgradelib#136]
When i execute openupgradelib from an openupgrade 7.0 version, i found errors due to this commit:
https://github.com/OCA/openupgradelib/commit/22a6409a5dc5946bea5e71e5124b3f7152f4106b

Lines like:
`obj = pool.get(model, False)
`or..
`if isinstance(pool, api.Environment):
`are failing because no api defined in 7.0.
I need to take a older commit to avoid this errors

**Comment by pedrobaeza** [comment]
This seems because `model` is not a valid one.

**Comment by pedrobaeza** [comment]
Should be fixed by #99
