### ISSUE TITLE
`invalidate_all` does not exist in Odoo >10.0

### ISSUE THREAD

**Issue by dbo-odoo** [OCA/openupgradelib#143]
Playing around with openupgrade and found a small issue here:
https://github.com/OCA/openupgradelib/blob/1a6c47e880f8d600edcf387a9a26c4a0c2956d05/openupgradelib/openupgrade.py#L2011

The environment's `invalidate_all` method has been removed as of odoo/odoo@32a58c0db

You probably want to do something like
``` python
env.cache.invalidate()
```
instead

Otherwise this method crashes and chunked operations are not possible ;)

**Comment by pedrobaeza** [comment]
Thanks for noticing!

As this was introduced for a method in OpenUpgrade in 10.0, it has passed unnoticed not being used in later versions. We still lack more test coverage of the methods across versions, but too much work to do in other fences before this. I'm doing a PR for fixing this.

**Comment by pedrobaeza** [comment]
Fix in #144

**Comment by dbo-odoo** [comment]
You have a PR ready in 1h on Easter Monday, this compensates your lack of testing quite nicely!
