### ISSUE TITLE
[RFC] create_workflow, set_workflow_activity

### ISSUE THREAD

**Issue by hbrunn** [OCA/openupgradelib#146]
I know it's a little bit late, but I wrote a [few functions](https://github.com/hbrunn/server-tools/blob/8.0-base_retrofit_workflow/base_retrofit_workflow/models/base_retrofit_workflow.py#L21) to activate a workflow without the workflow engine. As I dislike my original idea of making this a library addon, how do you feel about adding them here? I use this for in import, but I can imagine cases where this can come handy for migrations too.

**Comment by thomaspaulb** [comment]
Workflows are not a part of the newer Odoo versions, so maybe we leave it out of `openupgradelib` so as to not clutter it.

**Comment by pedrobaeza** [comment]
Indeed workflow engine is very outdated, but if you think it can be useful, you can put them here.

**Comment by hbrunn** [comment]
hmmm, it seems quite specific to our use case after all. I'll stash this for now, if ever I (or somebody else) need it in an OpenUpgrade context, we'll introduce it here.
