### ISSUE TITLE
convert_field_bootstrap_3to4: Should convert also translations of the field if any

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/openupgradelib#151]
The method must check if it's a translatable field (and what kind of translatable field - although in the end, it will mean more or only one `ir.translation` records -), and perform the conversion also on that translations. Example, field `website_description` in `product.template`.

**Comment by Yajo** [comment]
Do I need to implement that in both ORM and SQL modes? Or can I just drop the SQL one?
