### ISSUE TITLE
rename_columns: Misfiring of index rename when >63 chars

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/openupgradelib#172]
Indexes named according to the 'table_field_index' pattern are being renamed [here](https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L517). 

However when this leads to a very long (>63 chars) index name eg. [this one](https://github.com/OCA/OpenUpgrade/blob/10.0/addons/product/migrations/10.0.1.2/pre-migration.py#L13) leading to the command:

```
ALTER INDEX IF EXISTS "product_attribute_line_product_attribute_value_rel_val_id_index" RENAME TO "product_attribute_line_product_attribute_value_rel_product_attribute_value_id_index"
```

Then Postgres's [maximum identifier length](https://github.com/postgres/postgres/blob/master/src/include/pg_config_manual.h#L29) kicks in and the target name is now abbreviated to `product_attribute_line_product_attribute_value_rel_product_attr`, which can already exist - in this case because of the earlier rename for [product_attribute_line_id](https://github.com/OCA/OpenUpgrade/blob/10.0/addons/product/migrations/10.0.1.2/pre-migration.py#L12).

**Comment by kos94ok-3D** [comment]
Hi, @thomaspaulb.
Can close it?

**Comment by thomaspaulb** [comment]
@kos94ok-3D Yes it was solved.
