### ISSUE TITLE
UnicodeDecodeError at logged_query when query has unicode characters because of decode()

### ISSUE THREAD

**Issue by diggy128** [OCA/openupgradelib#180]
commit 868dcc6 adapted logged_query to work with psycopg2.sql.SQL and prints decoded query in order to make newline appear as a newline rather than a raw \n string (for python 3). This however fails when query has unicode characters with UnicodeDecodeError.

**Comment by pedrobaeza** [comment]
Any example?

**Comment by diggy128** [comment]
Sure.
Example query (when upgrading base from 8->9):
"UPDATE ir_actions SET help = '
<p class=''oe_view_nocontent_create''>Κάντε κλικ για να προσθέσετε μία νέα έγγραφο</p>
' WHERE id = 1783"

**Comment by Yajo** [comment]
Are we able to use Odoo's `ustr` just like in https://github.com/odoo/odoo/pull/35834?

**Comment by pedrobaeza** [comment]
I think so

**Comment by Yajo** [comment]
How do we import code from Odoo? Or maybe it's better to just copy or imitate that function to openupgradelib codebase?

**Comment by pedrobaeza** [comment]
This is executed inside Odoo itself, so the import is the same. Look at the beginning of the file how we are importing several Odoo Python modules
