### ISSUE TITLE
Change column type

### ISSUE THREAD

**Issue by sergiocorato** [OCA/openupgradelib#194]
Hi all, sorry for asking here (where is the right place?), where can I find an example to change a column from a type to another saving values? (boolean to selection in this case)
I'm proposing a PR on a module and would like to put the migration script too.
Thanks

**Comment by pedrobaeza** [comment]
In pre, you normally rename the source column.

In post, you use `map_values` or directly an SQL query for transforming data.

**Comment by sergiocorato** [comment]
Thanks
