### ISSUE TITLE
 [12.0] ValidationError(_('The user cannot have more than one user types.'))

### ISSUE THREAD

**Issue by sergiocorato** [OCA/openupgradelib#196]
Migration to 12.0 fails on user [constraint](https://github.com/OCA/OpenUpgrade/blob/0f34ee54afb5cef5e69dac04d5e01fab4eb303a3/odoo/addons/base/models/res_users.py#L396) on category user type, if there are users with portal + [user or public]

**Comment by pedrobaeza** [comment]
Why are you publishing this openupgradelib? This should be if the case in OCA/OpenUpgrade, not here. Any way, it's a data inconsistency that you must fix in previous version. 12.0 only forbids that inconsistency.

**Comment by sergiocorato** [comment]
Ops, sorry, i confused repo. Thanks
