### ISSUE TITLE
odoo 12 CE AttributeError: module 'odoo.tools' has no attribute 'yaml_import', even with pyyaml (3.13 or with 5.4.1)

### ISSUE THREAD

**Issue by Rai-Mohammed** [OCA/openupgradelib#238]
odoo12 CE module odoo.tools loading yaml_import, but there is no file /odoo/tools/yaml_import.py
The test when the file yaml_import.py don't exist for the corresponding versions of Odoo, must be included in /openupgradelib/openupgrade.py  

![odoo12 CE AttributeError module odoo tools has no attribute yaml_import](https://user-images.githubusercontent.com/59764135/117542172-75115400-b00f-11eb-9967-0049f7ae8b3d.png)
![odoo12 CE module odoo tools loading yaml_import](https://user-images.githubusercontent.com/59764135/117542176-78a4db00-b00f-11eb-9ea5-ded2dbe07371.png)

**Comment by Rai-Mohammed** [comment]
Issue reported in github and tweeter for OCA/openupgradelib :
odoo yaml_import tools.yaml_import AttributeError module 'odoo.tools' has no attribute 'yaml_import'

There is a difference between "pip openupgradelib" and "github openupgradelib" in the openupgrade.py
The correct one is from "github openupgradelib"
Updating openupgrade.py
nano /odoo_erp/odoo12ce/.local/lib/python3.7/site-packages/openupgradelib/openupgrade.py
{
if version_info[0] > 6 or version_info[0:2] == (6, 1):
    tools = core.tools
    SUPERUSER_ID = core.SUPERUSER_ID

    if hasattr(core, 'osv') and hasattr(core.osv, 'fields'):
        except_orm = core.osv.orm.except_orm
        many2many = core.osv.fields.many2many
        one2many = core.osv.fields.one2many

    if version_info[0] >= 7:
        plaintext2html = tools.mail.plaintext2html
    if version_info[0] >= 8:
        Many2many = core.fields.Many2many
        One2many = core.fields.One2many
        try:  # version 10
            from odoo.exceptions import UserError
        except ImportError:  # version 8 and 9
            from openerp.exceptions import Warning as UserError
    if version_info[0] < 12:
        yaml_import = tools.yaml_import
}

**Comment by pedrobaeza** [comment]
Are you installing library through `pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master`? Do you get the error in that one?

**Comment by Rai-Mohammed** [comment]
After installing the library through pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master
I have the latest version of openupgradelib-3.0.0, **and there is no errors.**
### You should mention this instruction as a hint installation in https://github.com/OCA/openupgradelib.git page.

Thanks you Mr. @pedrobaeza for the replay and the pip install instruction.
