### ISSUE TITLE
Enable auto-deployment via Travis

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/openupgradelib#24]
As in https://github.com/OCA/pylint-odoo/pull/2, we can enable auto-deployment to Pypi with Travis, like explained here:

http://docs.travis-ci.com/user/deployment/pypi/

And only activate it when making tags, so we can:

* Remove master and development branch.
* Control the moment when we want to make a release.
* Avoid to have someone with the corresponding credentials.

**Comment by StefanRijnhart** [comment]
Sounds great! That means the people who have branch permissions in GitHub can release. As you have the release powers currently, please go ahead!
