### ISSUE TITLE
Openupgradelib problems on Odoo.sh

### ISSUE THREAD

**Issue by alessandro-fiorino** [OCA/openupgradelib#242]
If an upgrade script using openupgradelib is run under odoo.sh, it throws warnings and fails with an error like the following example.
It happens with every module using openupgradelib in migration scripts, not just sale_order_type.
Openupgradelib is installed putting its name in the requirements.txt file as needed by odoo.sh.

2021-08-09 20:27:01,641 6 WARNING xxxx-test-14 py.warnings: /home/odoo/.local/lib/python3.8/site-packages/openupgradelib/openupgrade.py:59: DeprecationWarning: openerp is a deprecated alias to odoo.
  import openerp as core
 
2021-08-09 20:27:01,641 6 WARNING xxxx-test-14 py.warnings: /home/odoo/.local/lib/python3.8/site-packages/openupgradelib/openupgrade.py:60: DeprecationWarning: openerp is a deprecated alias to odoo.
  from openerp.modules import registry as RegistryManager
 
2021-08-09 20:27:01,641 6 ERROR xxxx-test-14 odoo.modules.migration: module sale_order_type: Each post-migration file must have a "migrate(cr, installed_version)" function

**Comment by pedrobaeza** [comment]
I'm afraid this is not something that can't be fixed at this side (at least not without losing features). Odoo.sh should allow other signatures. You should contact odoo.sh about this problem.

**Comment by alessandro-fiorino** [comment]
I think the problems starts with the two warnings about "import openerp" which I see had been fixed long ago.
Doing some investigation I've senn Odoo.sh uses the official pip repository so it's locked to version 2.0.0.
So this is another consequence of https://github.com/OCA/openupgradelib/issues/234
I'll add a note there.

**Comment by pedrobaeza** [comment]
I don't think publishing a new version will change this. They specifically say that the signature of the method should be the other, while we change for having directly a working environment, not only a DB cursor.

**Comment by alessandro-fiorino** [comment]
That signature is the official requirement of the odoo codebase not  only odoo,.sh, as stated in https://github.com/odoo/odoo/blob/14.0/odoo/modules/migration.py#L32
"Migrations files must be python files containing a `migrate(cr, installed_version) function"

**Comment by pedrobaeza** [comment]
Odoo code doesn't enforce that, only odoo.sh

**Comment by rvalyi** [comment]
Interesting enough, somebody reported the same problem today in OCA/l10n-brazil, we don't know if they are odoo.sh yet https://github.com/OCA/l10n-brazil/issues/1612

**Comment by alessandro-fiorino** [comment]
Seems it's doesn't happen only on odoo.sh
https://github.com/OCA/l10n-brazil/issues/1612#issuecomment-912122781

**Comment by pedrobaeza** [comment]
Well, I haven't been able to replicate it on on-premise installations.

**Comment by alessandro-fiorino** [comment]
IMHO the problem is for installations where it's not possible to force the installation of openupgradelib from github, so the one from the official pip repository is used.
The migrate decorator has been modified in openupgradelib 3.0 to automatically adapt the signature, as stated in the comments here https://github.com/OCA/openupgradelib/blob/ed01555b8ae20f66b3af178c8ecaf6edd110ce75/openupgradelib/openupgrade.py#L1826
In the pip repository there is still an old version of the library which doesn't have this capability.
So resolving this issue https://github.com/OCA/openupgradelib/blob/ed01555b8ae20f66b3af178c8ecaf6edd110ce75/openupgradelib/openupgrade.py#L1826 probably will solve also those one.

**Comment by pedrobaeza** [comment]
OK, I will check to publish such version to see.

**Comment by alessandro-fiorino** [comment]
Thanks a lot!
