### ISSUE TITLE
Missing dependency importlib_metadata from the requirements.txt (master branch)

### ISSUE THREAD

**Issue by jcdrubay** [OCA/openupgradelib#245]
Without importlib_metadata, I get this error
```
     File "/tmp/pip-req-build-02qq0x30/openupgradelib/__init__.py", line 14, in <module>
        from importlib_metadata import version, PackageNotFoundError
    ModuleNotFoundError: No module named 'importlib_metadata'
```

Just need to install the dependency: `pip install importlib_metadata`

**Comment by legalsylvain** [comment]
Hi. Did you tried with the last version of openupgradelib ? 

ref : recent PR : https://github.com/OCA/openupgradelib/pull/244
