### ISSUE TITLE
Can not install openupgradelib on Odoo 8.0 image

### ISSUE THREAD

**Issue by legalsylvain** [OCA/openupgradelib#288]
## Describe the bug

I try to install ``openupgradelib`` in the official [Odoo 8.0 docker image](https://hub.docker.com/layers/odoo/library/odoo/8.0/images/sha256-276bb1abe6130f272edb93e213455881b9a24421b1ca926cdc2f07c90aa0ef10?context=explore). 

I have the following error : 

```
odoo@e48d8eca34df:/$ python2 -m pip install openupgradelib
Downloading/unpacking openupgradelib
  Downloading openupgradelib-3.3.2-py2.py3-none-any.whl (67kB): 67kB downloaded
Downloading/unpacking cssselect (from openupgradelib)
  Downloading cssselect-1.1.0-py2.py3-none-any.whl
Downloading/unpacking importlib-metadata (from openupgradelib)
  Downloading importlib_metadata-4.11.3.tar.gz (43kB): 43kB downloaded
  Running setup.py (path:/tmp/pip-build-xrxfh5/importlib-metadata/setup.py) egg_info for package importlib-metadata
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-xrxfh5/importlib-metadata/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-build-xrxfh5/importlib-metadata/setup.py'
```

## To Reproduce

``docker run -it odoo:8.0 /bin/bash``

(then, in the container)

``python2 -m pip install openupgradelib``

## Additionnal element

- python2 version in the docker is quite obsolete. (2016)

```
$ python2
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
``` 
- when I create a python2 virtualenv  in my computer, I can install ``openupgradelib``.

```
virtualenv . --python=python2
. bin/activate
python2 -m pip install openupgradelib

$ python2
Python 2.7.18 (default, Mar  8 2021, 13:02:45) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

```

**Comment by rvalyi** [comment]
May be this workaround will do the trick. I did it again on a v9 last week:. https://github.com/OCA/openupgradelib/issues/248

**Comment by pedrobaeza** [comment]
We don't have this problem with Doodba 8.0, so check it for proper library versions needed.

**Comment by legalsylvain** [comment]
> We don't have this problem with Doodba 8.0, so check it for proper library versions needed.

could you provide the url of the github image of doodba 8.0 (dockerhub or whatever) ?

thanks.

**Comment by pedrobaeza** [comment]
https://github.com/Tecnativa/doodba/blob/416a249cde1ae4d869856af4bc5ebb5b8ca2a0c4/8.0.Dockerfile

**Comment by legalsylvain** [comment]
closing, as it's not a bug of openupgradelib.

thanks for your answer.
