### ISSUE TITLE
Documentation: lost documentation page https://doc.therp.nl/openupgrade/API.html

### ISSUE THREAD

**Issue by jcdrubay** [OCA/openupgradelib#293]
I have saved this URL https://doc.therp.nl/openupgrade/API.html
and it seems that we have no more an equivalent of that page in https://openupgradelib.readthedocs.io/en/latest/

Now the documentation is more than minimal.

Is there a way or plan to restore the old documentation?

Is there a plan to rewrite a new documentation?

**Comment by legalsylvain** [comment]
Hi @jcdrubay. I think you are mixing 2 things : 
- the documentation of openupgrade, previously hosted https://doc.therp.nl/openupgrade/API.html by therp here and that is now here https://oca.github.io/OpenUpgrade
- the documentation of openupgradelib project still here https://openupgradelib.readthedocs.io/en/latest/ (afaik)

Closing. Feel free to reopen if something is not clear.

kind regards.
