### ISSUE TITLE
How to work with version numbers when multiple PRs are opened?

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/openupgradelib#3]
As this package is now on Pypi, we need to increment the version number on each improvement, but if I have multiple PRs, I don't know the sequence in which they are going to be accepted. How others work with this question? Do they add the version change at merge time? Do they make dependent PRs?

**Comment by gdgellatly** [comment]
Maintain a seperate Release branch and merge periodically from master
updating version number is how gitflow sugests. Not every pr needs a
release. This could be scripted.

**Comment by bwrsandman** [comment]
Either that or periodically release.

An update to pypi (except for fixing the pip installation) should be done with a tag.

**Comment by bwrsandman** [comment]
develop branch added

**Comment by pedrobaeza** [comment]
OK, I understand the procedure.
