### ISSUE TITLE
potential refactor of openupgradelib in a few monthes (2022)

### ISSUE THREAD

**Issue by legalsylvain** [OCA/openupgradelib#307]
Hi following this information : https://www.youtube.com/watch?v=YoOaKvL3iKg&t=3049s

The migrations "helpers" will be free before the end of the years. These are "tools to write scripts".

I'm very curious to know what these tools will look like, but maybe some of them will be redundant with some functions of openupgradelib.

Maybe some convergence work will be needed.

kind regards.

Note : "OCA makes a great job to upgrade Community Edition databases", Odoo SA said. ;-)

**Comment by pedrobaeza** [comment]
We need to wait when they were released, and see if we wrap some of them in openupgradelib, replace or whatever, but I think they are good news indeed.

**Comment by legalsylvain** [comment]
Closing, as no helpers in recent versions, AFAIK.
