### ISSUE TITLE
[11.0] `rating_rating` does not have `parent_res_model` column

### ISSUE THREAD

**Issue by zamberjo** [OCA/openupgradelib#347]
## Describe the bug
The PR https://github.com/OCA/openupgradelib/pull/345 uses a column called `parent_res_model` which is added in odoo version 11.0. 

Since this is executed in the pre-migrations, this column does not exist and gives an error:
```bash
2023-09-13 22:42:01,349 1167 ERROR migration_db odoo.sql_db: bad query: UPDATE rating_rating SET parent_res_model='ir.actions.report' where parent_res_model='ir.actions.report.xml'
ERROR: column "parent_res_model" does not exist
LINE 1: ...ng SET parent_res_model='ir.actions.report' where parent_res...
```

## To Reproduce
Migrate an odoo10 to odoo11

---

Could we apply the following change?

```python
if table_exists(cr, "rating_rating"):
```
to 
```python
if column_exists(cr, "rating_rating", "parent_res_model"):
```

**Comment by zamberjo** [comment]
ping @pedrobaeza @duong77476 @legalsylvain

**Comment by pedrobaeza** [comment]
It should be both conditions. Can you please make a PR?

**Comment by zamberjo** [comment]
done
