### ISSUE TITLE
Data Validation by voluptuous

### ISSUE THREAD

**Issue by blaggacao** [OCA/openupgradelib#39]
This is really just a gimmick, but:
- the json-like spec approach seems to be best practice in the library.
- It could be more generalized and feature enriched by a small and simple data validation schema
- also this has small positive side effects on documentation.

Would this be something useful? (PR's accepted?)

**Comment by pedrobaeza** [comment]
The problem I see with any change is the backwards compatibility, so it can be considered for future functions, but not for the current ones.

**Comment by blaggacao** [comment]
@pedrobaeza I was thinking/dreaming about a general json dict wich could specify the whole migration set at once and then a wrapper function could validate and distribute. That would be nice, wouldn't it. Of course backwards compatibility is of utmost concern.

**Comment by pedrobaeza** [comment]
I'm not sure this is a good idea at all, because it will change everything in the way of developing migration scripts. Better to focus on making these scripts instead of reinventing the whole wheel.

**Comment by blaggacao** [comment]
@pedrobaeza Actually, it's not "reinventing the whole wheel", it would be just a wrapper "for the whole wheel". This means it is optional. It would map the way, I personally want to develop migration scripts. This is why I agree that backwards compatibility is of utmost concern.

**Comment by pedrobaeza** [comment]
I still don't see the benefit of this over the current flow, but why do you ask for opinion if at the end, you are going to do it anyway? Again, why don't you develop an OpenUpgrade migration script for any module instead of trying to change the way the actual developers of scripts do things?

**Comment by blaggacao** [comment]
@pedrobaeza What do you want to say with this?
I think you can be very confident, that once I need to develop a migration script, I will it feed to OpenUpgrade. Here we are concerned with OpenUpgradeLib, so I don't see what exactly you mean...

**Comment by pedrobaeza** [comment]
I'm saying that making practical contributions (OpenUpgrade migration scripts), you'll understand better why the things are like there, and then you'll be in position of proposing changes to the current state. This is not as today your current modus operandi.

**Comment by blaggacao** [comment]
@pedrobaeza It is true, I'm not contributing to OpenUpgrade so far (beside of the new Logo). This is because I don't need it. I think it is pointless to work on something which doesn't serve my interest. I'm using openupgradelib quite intensely ultimately and I guess I understand some things, others I don't. Based on what I understand, I have been told that anyone would be happy with well founded proposals and pull requests as long as I respect the license texts. I have also been told, that there are efforts in the OCA towards optimistic merging and collaborative WIP, because this might unleash collaboration and dynamic.

It is true, this idea is just that an idea, which would server my current use case and would make my life easier. I do not know if it would make life easier of those who actively develop migrations scripts, may be, may not be. So at least as to usefulness, this idea is Pareto Efficient, so I don't see a thumbgs down here.

Then again, you can argue, that this increases maintenance and that adding an external dependency is not good, as openupgradelib until now has nicely survived as a standalone. Standalone is tendentially a good thing so acknowledging this, we are out of pareto efficiency, so you could argue that you value the cost more than the benefits, which is perfectly legit and would be a very respectful reasoning.

However disqualifying "ad hominem" (in Grahams Pyramid of Disagreement) is not proof of good style and might eventually upset people, including me because I'm trying to make a honest proposal for improvement, which is an act of courtesy, as I'm trying to apport new ideas and concepts to a repository you provenly contribute regularly and therefore care about.

Thanks for having a look at, please: https://commons.wikimedia.org/wiki/File:Graham%27s_Hierarchy_of_Disagreement.svg

The contributing experience could be so much nicer for all parties.

**Comment by pedrobaeza** [comment]
David, I'm trying to be practical, not rude. You can see that one PR that makes something interesting, has been reviewed properly. Or your logo was quickly accepted and welcomed (thanks again for it). Other things, being discarded in an early stage makes all free for making another things in our stretched time.

If you don't use OpenUpgrade, you are losing the main target for this library, among with the migration scripts for modules in between versions, so again your focus should be there. If you're trying to make something totally different (or maybe something similar, but totally different in the execution), maybe you should start another project/library instead of trying to alter this one the way you want. This library has a lot of years (well, not as library, but integrated in OpenUpgrade distribution), and has proven to be very effective in what it tries to do. Changing the way things are done after all these years is something that we shouldn't do, or at least not without strong reasons.

**Comment by blaggacao** [comment]
OK, the purpose we are using it is for live migration for every module we build, we immediately build migrations scripts, too. Until recently, we have been working on raw SQL, but this doesn;t fit any more and s too time consuming. So we need a library. Of course we can just mix and match, but then our work would never ever benefit someone else. 
Among the whole ecosystem, openupgradlib is probably the most appropriate point for this. And I'm really not interested in forking openupgradelib, just because people here block contribution. 

Beware: All I propose is carefully crafted for backwards compatibility, it seems by saying "changing the way things are done after all these years" you refer rather to a personal feeling than a truthy argument. Thos commits do not change anything at all of how things have been done in the past, but open up extra possibilities. So in that it is pareto efficient. I feel you are not acknowledging that point, but rather elaborate non-precise argument. If you could say, "well, there is something about what this guy is saying", then you probably more likely to be able to follow my reasoning and understand the strong reasons, or where you don;t see them, I definitely merit a chance to show them to you (and others).
It's in the interest also of making this repo a nice and friendly place. Well if the objective is to freez it for ever and preclude it from any evolution, than the current approach to contributors might be very effective. (I might link the contributing stats here, it's unfortunately still not a hotspot)

**Comment by StefanRijnhart** [comment]
"a general json dict wich could specify the whole migration set at once and then a wrapper function could validate and distribute" -> Honestly, I have know idea how this relates to the current process.

**Comment by StefanRijnhart** [comment]
Does that mean that you want to try to express funcionality like 'create quants for existing stock moves' like we did in OpenUpgrade 8.0 in a JSON dict?

**Comment by blaggacao** [comment]
@StefanRijnhart 
One of my migrations scripts looks like this:
```
@mig.migrate()
def migrate(env):
    reload(mig)
    fiscal_ciiu_1_map = {
        'to_model': 'res.partner',
        'ex_field': mig.l(env, 'fiscal_ciiu_1'),
        'to_field': 'fiscal_ciiu_1',
        'xml_ids': True,
        'mapping': mapping
    }
    fiscal_ciiu_map = {
        'to_model': 'res.partner',
        'ex_field': mig.l(env, 'fiscal_ciiu'),
        'to_field': 'fiscal_ciiu',
        'xml_ids': True,
        'mapping': mapping
    }

    mig.map_values_orm(env, fiscal_ciiu_1_map, check_completeness=True)
    mig.map_values_orm(env, fiscal_ciiu_map, check_completeness=True)
```

It's still rather straight forward, but I can think of cases in the near future where I would need to do a (metonymy:) series of copy, map, copy again, merge, delete etcetera operations. The exposed idea can then be seen as a rather small convenience step to have the whole migrations instruction in a json-ish dict and call one wrapper method which takes care of the execution.

**Comment by StefanRijnhart** [comment]
I now start to think that maybe you should start your own library. It does not seem to me that OpenUpgrade's goal and yours are much aligned.

**Comment by blaggacao** [comment]
I won't...
