### ISSUE TITLE
Rollback when failing migration

### ISSUE THREAD

**Issue by blaggacao** [OCA/openupgradelib#41]
I've decorated the migration method like so:
```
from openupgradelib import openupgrade as ou
@ou.migrate()
def migrate(cr, version):
```
Yet, when the migration fails (on the post script of a module), nothing is rolled back. Is that expected behaviour? Would there be a way to roll back a failing migration automatically.

**Comment by pedrobaeza** [comment]
AFAIK, that decorator is not for that. It only serves to avoid the lines:
```
if not version:
    return
```

**Comment by pedrobaeza** [comment]
Anyway, the rollback should be performed at module level. This means that everything performed in the current module migration is undone, but not the steps of previous modules, so for me it's the correct behavior.
