### ISSUE TITLE
copy_column warranted?

### ISSUE THREAD

**Issue by blaggacao** [OCA/openupgradelib#42]
As stated, I'm working on the implementation of a ORM rename_column to enable 2many and possibly property fields. While seems right now easy to rename a column to a manual one, which then gets initialized properly by the ORM at module loading time (so the plan), copying a column is slightly more complex (because construction and resolution of 2many table and columns, as well as data copying as the new field would initialize empty at first).
On the other hand the only use case of copy column, I can really think about is:

1. Copy a column
2. Do something with one of the columns, one functioning as source and one as destination)
3. source means basically "backup" in most cases, and in all sane cases means "inmutable"
4. destination means "transformation and storage for future use"

This can also be achieved in an ORM compatible way like this:

1. Rename column (ORM)
2. Let your model create the new column
3. map_values_orm 1 to 2

In this order of ideas, it could be argued, that copy_column could be deprecated in future version for the sake of uniformity and simplicity. 

However, it is not imminent to create a compatibility wrapper, as the proposed workflow plays with the ORM loading behaviour and is not easily alterable in the scope of a wrapper.

What do you think in general and in detail?

**Comment by pedrobaeza** [comment]
I don't get the use case nor the explanation of your rationale. Please explain an exact case that is not achieved with current implementation and how this solution would help with that case.

**Comment by blaggacao** [comment]
I'm sorry, additionally I got it the wrong way. It is that copy_column, when done through ORM has an implicit rename_column functionality, when the module loading kicks in and does it's cleaning (except for stale relational tables, that iirc for some reasons do not get cleaned up).

**Comment by blaggacao** [comment]
@pedrobaeza It becomes probably clearer once a PR for the ORM copy get's ready. We can discuss the usefulness of orm_copy there at the given time.
