### ISSUE TITLE
[9.0] Use of the environment doesn't work?

### ISSUE THREAD

**Issue by ecino** [OCA/openupgradelib#73]
Impacted versions: 9.0

Steps to reproduce: 
Make a migration script using @openupgrade.migrate(use_env=True) decorator
Call env.ref('module.xml_id') function or env['model'].search() and it doesn't work.

Current behavior:
For instance, calling `env['res.partner'].search([('ref', '=', '123')])`
{ValueError}Invalid field 'ref' in leaf "<osv.ExtendedLeaf: ('ref', '=', 'lsv') on res_partner (ctx: )>"

Expected behavior:
Find a res.partner record.

I tried this in a custom module pre-migration and I'm only doing this search in the migrate function which gives me this error.

**Comment by pedrobaeza** [comment]
It's not a problem of env, but the field is not available in that stage, as said by the error.
