### ISSUE TITLE
pypi failed

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/openupgradelib#76]
pypi Travis stage (for publishing to pypi) is failing and I'm not sure why:

https://travis-ci.org/OCA/openupgradelib/jobs/270853280#L547

@moylop260 any idea?

**Comment by moylop260** [comment]
This job ran on Trusty environment:
 - <img width="1231" alt="screen shot 2017-09-01 at 10 38 20" src="https://user-images.githubusercontent.com/6644187/29976373-6ca2255e-8eff-11e7-8f31-1183eb4b1382.png">

`TRAVIS_PYTHON_VERSION` is not set with `2.7` for pypi job:
 - <img width="1084" alt="screen shot 2017-09-01 at 10 39 18" src="https://user-images.githubusercontent.com/6644187/29976421-916b1288-8eff-11e7-8d5a-56c5850c2351.png">

The fixes could be:
 - Option A: Force use of `dist: precise`
 - Option B: Get python version using `$(python -c 'import sys; print(sys.version_info[:2])') == "(2, 7)"`
