### ISSUE TITLE
set_defaults method

### ISSUE THREAD

**Issue by mreficent** [OCA/openupgradelib#78]
Hi @hbrunn @pedrobaeza !

I want to use the 'set_defaults' method in v10.

In v10 this method breaks in this line https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L652 because `.search()` in new api only has `domain` but not `cr` nor `user_id`.

Could you update this method to be usable in old versions but also in v10?

Let's update this method ASAP, if possible :smiley:

Thanks!

**Comment by hbrunn** [comment]
I usually work on stuff that either intrigues me or some customer needs, and this one falls in neither category. But I'm always happy to help out fellow developers with some pointers, so I'd suggest you come up with your own version of this. Check `version_info`, and depending and what you get there, either call the v7 version or v8. Or even simpler, starting from 10, what is called `pool` here actually is an `Environment`. Just check the type and react on this accordingly.

**Comment by hbrunn** [comment]
you should btw also look at https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L662, and also check the field's `default` attribute in `>=v8`, we missed this one probably because upstream only really uses the new api in 10 extensively.

**Comment by jbeficent** [comment]
Many thanks!ñ for the tips! We will try to figure out a new method for v10.

**Comment by mreficent** [comment]
@hbrunn Here it's my PR: https://github.com/OCA/openupgradelib/pull/79.

**Comment by StefanRijnhart** [comment]
Closing this as the PR was merged. Thanks!
