### ISSUE TITLE
migration database odoo 11 with OpenUpgrade AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by AMhadhbi** [OCA/openupgradelib#97]
Hello when I ran the server, I have this issue.  
File "/home/vagrant/.local/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 1204, in wrapped_function
    (module, filename, str(e).decode('utf8')))
**AttributeError: 'str' object has no attribute 'decode'**

**Comment by pedrobaeza** [comment]
Which function?

**Comment by AMhadhbi** [comment]
@pedrobaeza 
Traceback (most recent call last):
  File "/var/www/odoo/service/server.py", line 925, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/www/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/www/odoo/modules/loading.py", line 416, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/www/odoo/modules/loading.py", line 307, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/www/odoo/modules/loading.py", line 139, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/var/www/odoo/modules/migration.py", line 178, in **migrate_module**
    migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade.py", line 1204, in wrapped_function
    (module, filename, str(e).decode('utf8')))
AttributeError: 'str' object has no attribute 'decode'

**Comment by pedrobaeza** [comment]
OK, it should be the `migrate` function then (you are still not saying to me), but we have the initial migration activated in OpenUpgrade without problems... Please check Travis in OpenUpgrade.

**Comment by AMhadhbi** [comment]
Yes you are right, I found previous issue before this  
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade.py", line 1200, in wrapped_function
    if use_env2 else cr, version)
  File "/var/www/addons/account/migrations/11.0.1.1/pre-migration.py", line 19, in migrate
    openupgrade.delete_record_translations(env.cr, 'account', [
**AttributeError: module 'openupgradelib.openupgrade' has no attribute 'delete_record_translations'**

but I clone from the master and I install openupgradelib
- git clone https://github.com/OCA/openupgradelib.git
- sudo python3 setup.py install

I see the function delete_record_translations in openupgradelib/openupgrade.py but in /usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade.py doesn't exist

**Comment by pedrobaeza** [comment]
Yeah, but that's something not connected. It's because the version published in pypi is not the last one. Where do you want to get to?

**Comment by AMhadhbi** [comment]
I want to migrate database version 10 to 11so I ran the server with OpenUpgrade with copy open pull request module account - By @rruebner - #1195 , because module account not already merged.

**Comment by AMhadhbi** [comment]
I will check it again, it is good  to copy current matser openupgradelib in repo  with c**p -r openupgradelib/*  /usr/local/lib/python3.5/dist-packages/openupgradelib** because pypi is not the last one?

**Comment by pedrobaeza** [comment]
No, you just need to install it properly from source. Use `pip3 install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master`
