### ISSUE TITLE
pip release for missing rename_fields api

### ISSUE THREAD

**Issue by pniederlag** [OCA/openupgradelib#98]
First of all, thx for maintaining and publishing the OpenUpgrade effort.

My suggestion/wish is to create a fresh release of openupgradelib.

Rationale:

This commit 
https://github.com/OCA/openupgradelib/commit/954121e0c353444b8511890193b08cf8f3c11797 introduced a new api "rename_fields", that seems not to be part of the latest pip release (1.3.2). However this API is used by the OpenUpgrade Repo (on 9.0 with https://github.com/OCA/OpenUpgrade/commit/ba519edb915bf3eaf8a). So currently we need a source install of openupgradelib to use OpenUpgrade. ;(

So about shipping out a fresh release?

Regards,
Peter

**Comment by pedrobaeza** [comment]
Use `pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master` for having latest version.
